### ISSUE TITLE
OpenAIComputed and Models module overloads F# "list" postfix type generic type specifier

### ISSUE THREAD

**Issue by JustinWick** [yazeedobaid/openai-fsharp#1]
`'a list` is one of the most basic and pervasive parts of `FSharp.Core`, and overloading this is unnecessarily confusing to new users of openai-fsharp, especially those still learning F# itself. It is also likely irksome to veteran F# users, who are used to that term having a _very_ specific meaning as part of the standard type system.

When reading the example CE, I legitimately though that that it was a convenience specifier for the generic type to be returned (`list`, `array`, `option`, etc) that was expected to be returned.

Perhaps use the slightly more verbose but specific `listModules`?

**Comment by yazeedobaid** [comment]
I don't fully understand the issue description. Are you referring that the `list` property on CE builder will be confused with `list` method that is used to create/initialize/return a list in F#?

If that is the case, then I don't see the confusion, since that property is inside the CE builder, and its intention to be read as, set the context to `models`, then use `list` API. Reading it from top-to-bottom.

Also, I didn't want to go with `listModels`, since repeating word models seem to clutter the library API, hence I created the context switchers, `'models`, and `edits` properties for example. Which will drop the repeating resource name and focus on API need itself, like `list`.

**Comment by yazeedobaid** [comment]
Thanks for opening the issue, I'm going to close it, as explained in the previous comment, the API is in the context of `openAI` builder object so should not be confused with F# constructs.

**Comment by brianberns** [comment]
I think the problem here is that the `Models.list` function hides the `list` type, even if you're not using the `openAI` builder. One way to avoid this is to remove the `open OpenAI.Models` line, which forces qualified references to `Models.list`.

**Comment by JustinWick** [comment]
Just for posterity here, I'm not talking about the `list` function to create a list in F#, I'm talking about the type specifier suffix, ala:
`let myList : int list = []`

This is tantamount to being a language keyword, and it feels rather wrong to shadow it.
